### ISSUE TITLE
Check if modeler plugin still works with Camunda Modeler 5.x

### ISSUE THREAD

**Issue by gclaussn** [camunda-community-hub/bpmn-driven-testing#114]
Due to the release of Camunda Modeler 5.x, the workings of the modeler plugin must be verified.

**Comment by gclaussn** [comment]
The modeler plugin works with 5.7.0 after a minor fix. Moreover the usage of the plugin for Camunda Platform 8 BPMN diagrams was prevented. To disable the menu action, this issue waits for: https://github.com/camunda/camunda-modeler/issues/3458

**Comment by gclaussn** [comment]
Waits for Camunda Modeler 5.8.0 to be released.

**Comment by talesmp** [comment]
@gclaussn the attributes "Name" (<bpmndt:name>) and "Description" (<bpmndt:description>) of the Test Cases stopped from Modeler 5.0.0 onwards, while it still works properly on Modeler 4.12.0.

**Comment by gclaussn** [comment]
@talesmp thank you for that information. I did some manual checks and probably missed that.

**Comment by gclaussn** [comment]
@talesmp do you have some error message or screenshot for me? I checked it with Camunda Modeler 5.7.0 - names and description are saved to the XML and loaded from the XML.

**Comment by talesmp** [comment]
@gclaussn v0.7.0 works perfectly! regarding the yesterday's comment, it had no error logs, but the behaviour was: 
- you were able to trigger the "Edit `Name` and `Description`" panel after clicking on the pencil;
- but it didn't matter how much you wrote on both fields, only one single character would be saved under `Name`, and one single character under `Description`;

Just to be clear, this was fixed in the version released 2 weeks ago (v0.7.0)! ;-) 
But, if by any means you want to see the behaviour I mentioned above, it will be my pleasure to hop on a call with you and share my screen.
