### ISSUE TITLE
[Question] Regardings External Tasks executed in parallel

### ISSUE THREAD

**Issue by nyuuyn** [camunda-community-hub/bpmn-driven-testing#200]
Hi,

just wanted to ask if there is a standard approach when facing External Task that run in parallel, when customizing the TestExecutors, e.g., like here:

![grafik](https://github.com/user-attachments/assets/1de47e93-c217-43c0-a36d-c6d683d73102)

If I understand correctly the plugin tries to use simple flows through the model, and therefore omits creating parallel paths.
However, in the case shown, I get the problem that the process never can go past the merging gateway.
In the repository there is an example with Delegates, however, in this case we have External Tasks.

If I understand the framework completly I should now create my own ExternalTaskHandler, e.g., like this:

```
ExternalTaskHandler extTaskHandler = new ExternalTaskHandler(tc.getProcessEngine(), "ActivityId", "TopicName");
tc.createExecutor().execute();
```

But what I am missing is: how can I customize the executor so that the ExternalTaskHandler is executed in the test?

Any help would be appreciated!

**Comment by gclaussn** [comment]
hi @nyuuyn,

after selecting the path and adding the test case. please go to the BPMN XML and add the parallel element as node to the test case (I manually added the selected line):
![image](https://github.com/user-attachments/assets/4214c120-5e72-47b9-9df5-2b6473692aca)

when this is done, the test case gets a problem marker ("Path is invalid...") - but you can ignore it, since this is only related to the path finding:
![image](https://github.com/user-attachments/assets/363ba1b7-6920-482e-9a91-a3e0432a71de)

now the test code generation should consider the second external task (generate a handle* method, handle its wait state, assert that the process instance has passed it). please keep in mind that the execution order is fixed - in my example: first "externalTaskA", second "externalTaskB".

i hope this helps!

best regards

**Comment by nyuuyn** [comment]
Ahhh great, thank you very much! I didn't think that would even work :D
