### ISSUE TITLE
How can I run webpack in my Camunda modeler?

### ISSUE THREAD

**Issue by laurenzhinterholzer22** [camunda-community-hub/bpmn-driven-testing#49]

**Comment by gclaussn** [comment]
hello @laurenzhinterholzer22, can you please describe what you want to achieve and whats the problem/error?

**Comment by laurenzhinterholzer22** [comment]
I am trying to run your project and you describe in your Camunda Modeler Plugin README.md to "Run webpack to build dist/client.js on the fly, when saving changes" (Step 4) but I don't know how to do that. Btw I am using MacOS

**Comment by gclaussn** [comment]
If you want to use the plugin within your Camunda Modeler, just perform step 1 to 5 - this will be enough.

If you want to do plugin development (make adjustments, enhancements or play around with the code), you need to a NodeJS 14.x installation, which includes `npm`. In your terminal, change into the camunda-modeler-plugin directory, install the required dependencies via `npm install` and run the webpack build via `npm run dev`. If you now change something in the code, webpack will automatically build the project for you. So that you just need to reload the Camunda Modeler (like described). This allows fast roundtrips for rapid development.

I will some more details to the README to make it more clear!

**Comment by laurenzhinterholzer22** [comment]
When I run nom run dev I get this error:
laurenzhinterholzer@MacBook-Pro-von-Laurenz bpmn-driven-testing-plugin % npm run dev

> bpmn-driven-testing-plugin@1.0.0 dev
> dist/client.js

dist/client.js: line 1: syntax error near unexpected token `function'
dist/client.js: line 1: `/******/ (function(modules) { // webpackBootstrap'

**Comment by laurenzhinterholzer22** [comment]
I have another problem:
Because I didn't manage to  automatically store the bpmns in the project I tried to copy the XML Code which was generated through selection of the test case in the plugin in Camunda. Copied the code into a .bpmn file and stored it in the project (maven-plugin/src/main/ressources). But when I run: "BPMN-driven-testing:generator I get a build failure: 

[INFO] Found BPMN file: orderprocess.bpmn
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.980 s
[INFO] Finished at: 2021-11-25T17:48:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.camunda.community:bpmn-driven-testing-maven-plugin:0.3.0:generator (default-cli) on project bpmn-driven-testing-maven-plugin: Unexpected error occurred: SAXException while parsing input stream: Fatal Error: URI=null Line=1: Präfix "bpmn" für Element "bpmn:process" ist nicht gebunden. -> [Help 1]

**Comment by gclaussn** [comment]
Regarding your first problem: Do you want to use the plugin or do some plugin development? Did the error occur in your terminal or in the Camunda Modeler console/log output? Have you executed `npm install` before?

Regarding your second problem: It seems that your BPMN XML is not complete.

We can do a Google meet session if you want:
https://meet.google.com/src-zfjg-jnz
